apiVersion: v1
kind: ConfigMap
metadata:
  name: sarvavaidya-config
  namespace: sarvavaidya
data:
  NODE_ENV: "production"
  PORT: "3001"
  FRONTEND_URL: "http://sarvavaidya.local"
  APP_URL: "http://sarvavaidya.local"
  PINECONE_INDEX: "quickstart"
  PINECONE_NAMESPACE: "medical_ai_diseases"
  PINECONE_DIMENSION: "1536"
